# Generated by Django 3.2.8 on 2021-11-03 03:41

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMod',
            fields=[
                ('speed', models.IntegerField(default=0)),
                ('avg_speed', models.IntegerField(default=0)),
                ('temperature', models.IntegerField(default=0)),
                ('fuel_level', models.IntegerField(default=0)),
                ('engine_status', jsonfield.fields.JSONField(default=dict)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
